#lunching instance with local laptop keypair generated by ssh-keygen
resource "aws_key_pair" "key" {
    key_name = "localkey"
    public_key = file("~/.ssh/id_ed25519.pub")
}

#attaching keypair to the instance
resource "aws_instance" "keyinstance" {
    ami = "ami-01376101673c89611"
    instance_type = "t2.micro"
    key_name = aws_key_pair.key.key_name
    tags = {
      Name = "keypair-instance"
    }


#conneting to ec2-instance by local laptop keypair
connection {
    type        = "ssh"
    user        = "ec2-user"  # Replace with the appropriate username for your EC2 instance
    # private_key = file("C:\Users\Mahendhar Emmadi\.ssh\keyfilename")
    private_key = file("~/.ssh/id_ed25519")  #private key path
    host        = self.public_ip
}

#local file creation
provisioner "local-exec" {
    command = "touch file1"
}

#remote file creation
provisioner "remote-exec" {
    inline = [ 
        "touch file2",
        "echo 'adding sum content to the file by using command' >> file2"
    ]
}

#file provisioner creating file in local copying to the remote instance
provisioner "file" {
    source = "file1"
    destination = "/home/ec2-user/file1"
}
}